name: Deploy Preview

on:
  workflow_dispatch:

  push:
    branches: [ main ]

permissions:
  contents: read
  id-token: write

jobs:
  deploy-preview:
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: preview
    secrets: inherit
