name: Deploy Preview

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  deploy-preview:
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: preview
    secrets: inherit
